# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDestinationNegative():
  def setup_method(self, method=None):
    self.driver = webdriver.Firefox(executable_path=r'C:/geckodriver.exe')
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_destinationNegative(self):
    self.driver.get("http://127.0.0.1:8000/user/index")
    self.driver.set_window_size(1434, 732)
    time.sleep(5)
    self.driver.find_element(By.NAME, "destination").click()
    self.driver.find_element(By.NAME, "destination").send_keys("123")
    time.sleep(1)
    self.driver.find_element(By.ID, "sub").click()
    self.driver.find_element(By.CSS_SELECTOR, ".warning").click()
    time.sleep(1)
    self.driver.close()
  
if __name__ == '__main__':
    # ! main方法中进行调用
    test = TestDestinationNegative()
    test.setup_method()
    test.test_destinationNegative()
    time.sleep(2)
    # 关闭程序
    test.teardown_method()
