# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCheckoffPositive():
  def setup_method(self, method=None):
    self.driver = webdriver.Firefox(executable_path=r'C:/geckodriver.exe')
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_checkoffPositive(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1434, 703)
    self.driver.find_element(By.CSS_SELECTOR, ".fa-bars").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) > a").click()
    self.driver.execute_script("window.scrollBy(0,{})".format(600))
    time.sleep(2)
    self.driver.find_element(By.NAME, "hotel_date").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pmu-sunday:nth-child(7)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pmu-days > .pmu-button:nth-child(8)").click()
    self.driver.find_element(By.ID, "destination").click()
    self.driver.find_element(By.ID, "destination").send_keys("Singapore, Singapore")
    self.driver.find_element(By.ID, "sub").click()
    time.sleep(10)
    self.driver.find_element(By.CSS_SELECTOR, "form:nth-child(3) button").click()
    time.sleep(1)
    self.driver.execute_script("window.scrollBy(0,{})".format(1200))
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "form:nth-child(2) span").click()
    self.driver.find_element(By.ID, "salutation").click()
    dropdown = self.driver.find_element(By.ID, "salutation")
    dropdown.find_element(By.XPATH, "//option[. = 'Mr.']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#salutation > option:nth-child(2)").click()
    self.driver.find_element(By.ID, "fname").click()
    self.driver.find_element(By.ID, "fname").send_keys("a")
    self.driver.find_element(By.ID, "lname").click()
    self.driver.find_element(By.ID, "lname").send_keys("b")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("100@gmail.com")
    self.driver.find_element(By.ID, "phone").click()
    self.driver.find_element(By.ID, "phone").send_keys("84634785")
    self.driver.find_element(By.ID, "message").click()
    self.driver.find_element(By.ID, "message").send_keys("None")
    self.driver.find_element(By.ID, "card_number").click()
    self.driver.find_element(By.ID, "card_number").send_keys("123456789")
    self.driver.find_element(By.ID, "card_name").click()
    self.driver.find_element(By.ID, "card_name").send_keys("abc")
    self.driver.find_element(By.ID, "exp_month").click()
    dropdown = self.driver.find_element(By.ID, "exp_month")
    dropdown.find_element(By.XPATH, "//option[. = 'January']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#exp_month > option:nth-child(2)").click()
    self.driver.find_element(By.ID, "exp_year").click()
    dropdown = self.driver.find_element(By.ID, "exp_year")
    dropdown.find_element(By.XPATH, "//option[. = '2022']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#exp_year > option:nth-child(2)").click()
    self.driver.find_element(By.ID, "CVV").click()
    self.driver.find_element(By.ID, "CVV").send_keys("101")
    self.driver.find_element(By.ID, "billing_address").click()
    self.driver.find_element(By.ID, "billing_address").send_keys("abc")
    self.driver.find_element(By.ID, "submitDetails").click()
    self.driver.find_element(By.CSS_SELECTOR, "h2").click()
    self.driver.close()

if __name__ == '__main__':
# TestDestinationNegative testing
    test = TestCheckoffPositive()
    test.setup_method()
    start = time.time()
    test.test_checkoffPositive()
    print('******************run success time is '+ str(time.time()-start))
    time.sleep(2)
    # 关闭程序
    test.teardown_method()