# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDestinationPositive():
  def setup_method(self, method = None):
    self.driver = webdriver.Firefox(executable_path=r'C:/geckodriver.exe')
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_destinationPositive(self):
    self.driver.get("http://127.0.0.1:8000/user/index")
    self.driver.set_window_size(1434, 632)
    time.sleep(3)
    self.driver.find_element(By.NAME, "destination").click()
    self.driver.find_element(By.NAME, "destination").send_keys("London, England, UK (LGW-Gatwick)")
    time.sleep(3)
    self.driver.find_element(By.ID, "sub").click()
    self.driver.find_element(By.CSS_SELECTOR, ".box:nth-child(3) .describe").click()
    self.driver.close()
  
if __name__ == '__main__':
    # TestDestinationPositive testing
    test = TestDestinationPositive()
    test.setup_method()
    start = time.time()
    test.test_destinationPositive()
    print('run success time is '+ str(time.time()-start))
    time.sleep(2)
    # 关闭程序
    test.teardown_method()
    