# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLoginNegative():
  def setup_method(self, method=None):
    self.driver = webdriver.Firefox(executable_path=r'C:/geckodriver.exe')
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_loginNegative(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1434, 701)
    self.driver.find_element(By.CSS_SELECTOR, ".fa-bars").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) > a").click()
    self.driver.find_element(By.ID, "emailadd").click()
    self.driver.find_element(By.ID, "emailadd").send_keys("100@gmail.com")
    self.driver.find_element(By.ID, "passwd").click()
    self.driver.find_element(By.ID, "passwd").send_keys("Wy1379707007")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text:nth-child(1)").click()
    self.driver.close()
  
if __name__ == '__main__':
# TestDestinationNegative testing
    test = TestLoginNegative()
    test.setup_method()
    start = time.time()
    test.test_loginNegative()
    print('run success time is '+ str(time.time()-start))
    time.sleep(2)
    # 关闭程序
    test.teardown_method()