# Generated by Selenium IDE
from cProfile import label
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import matplotlib.pyplot as plt

class TestTestcache():
  def setup_method(self, method=None):
    self.driver = webdriver.Firefox(executable_path=r'C:/geckodriver.exe')
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_testcache(self):
    self.driver.get("http://127.0.0.1:8000/user/bookHistory")
    self.driver.set_window_size(1392, 704)
    for i in range(20):
        self.driver.find_element(By.LINK_TEXT, "Home").click()
        self.driver.find_element(By.LINK_TEXT, "Book History").click()
    self.driver.close()
  

if __name__ == '__main__':
# TestDestinationNegative testing
    test = TestTestcache()
    test.setup_method()
    start = time.time()
    test.test_testcache()
    print('--------------------------------------------')
    print('run success time is '+ str(time.time()-start))
    time.sleep(2)
    # 关闭程序
    test.teardown_method()
    name_list = ['Without cache','Using cache']
    first_type = [14.38730239868164,14.557264566421509]
    num_list = [86.38730239868164,6.557264566421509]
    plt.bar(range(len(num_list)), first_type,tick_label=name_list,label='first',fc='y')
    plt.bar(range(len(num_list)), num_list, bottom=first_type, label='later',tick_label = name_list,fc = 'r')
    plt.legend()
    plt.show()  